services:
  demo:
    image: demo-app:v0
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/test_db
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml/:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
